//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLayer.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int id { get; set; }
        [Display(Name ="Ad Soyad")]
        public string name_surname { get; set; }
        [Display(Name ="Telefon Numarasý")]
        public string phone_number { get; set; }
        public Nullable<int> departman_id { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
